### ISSUE TITLE
Netflix failed to load history

### ISSUE THREAD

**Issue by VND2008** [trakt-tools/universal-trakt-scrobbler#435]
### Expected Behavior

Every time I go to history page it says “failed to load history” and in a split second it goes back to selecting a streaming service to sync page. 

I have tried removing and reinstalling extension, disconnecting and reconnecting netflix on UTS, cleared cache and storage, changed browers, no VPNs. 

https://github.com/user-attachments/assets/a24cf8c3-f736-4ec9-a2a4-dad74ecbdd74

### Additional Information

- **Windows 10 Enterprise + Version 22H2**
- **Brave 1.81.137, Firefox 142.0.1**
- **UK**

**Comment by anks-mrangry** [comment]
@VND2008 This is fixed and merged with #433. You need to use the Beta release.

**Comment by csaavedra** [comment]
This still fails for me, is the fix still in beta?

**Comment by syllant** [comment]
@csaavedra On my side, I confirm it now works fine with the beta (2025-10-16T21:21:46.216Z)

**Comment by eldonzo** [comment]
I installed the beta, but it didn't solve the issue.

I get this error:

history.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at history.js:2:311609
    at h (history.js:2:292632)
    at Generator.<anonymous> (history.js:2:293974)
    at Generator.throw (history.js:2:293061)
    at e (history.js:2:301266)
    at l (history.js:2:301505)

**Comment by VND2008** [comment]
@anks-mrangry how do i download beta version, i don't get to see it on firefox extension store or anywhere else

**Comment by anks-mrangry** [comment]
> [@anks-mrangry](https://github.com/anks-mrangry) how do i download beta version, i don't get to see it on firefox extension store or anywhere else

@VND2008 You can download beta version under Releases.

![Image](https://github.com/user-attachments/assets/187f00e5-cf3f-4582-9ee7-a1f9f4180706)

**Comment by csaavedra** [comment]
WFM with the beta.

**Comment by mwilkinson22** [comment]
Is there an ETA for this getting into a new version please? As near as I can tell I can't install the beta as it's unverified and I'm not running a dev/nightly build of Firefox

**Comment by psxlover** [comment]
@mwilkinson22 you don't need a dev/nightly build of firefox, you can run it in the normal release (I think it just resets after each restart).

Nevertheless I will ask the same question as mwilkinson22, any plans on releasing a new version? @rafaelgomesxyz it's been 4.5 months since Netflix syncing started failing, and 3 months since #426 was merged.

**Comment by rafaelgomesxyz** [comment]
@psxlover So sorry, I kept putting it off and forgetting. I just uploaded a new version to the Chrome and Firefox stores, they're in the process of being reviewed before they can go live.

**Comment by mwilkinson22** [comment]
Working for me now, thanks!

**Comment by MrMamen** [comment]
Closing as this has been fixed and released to the stores.

**Comment by AcidSlide** [comment]
> Closing as this has been fixed and released to the stores.

Can confirm latest beta is working with the latest fix for Netflix
